fix LocalMetricCollector registerJMX
skiptests/astraea pull request #1536
Opened 2023-03-03 12:09 UTC by harryteng9527

resolve https://github.com/skiptests/astraea/issues/1535#issue-1608506791

2023-03-03 13:28 UTC, chinghongfang requested changes
感謝 @harryteng9527 幫忙修正！
不過似乎多了一個空的檔案(app/.attach_pid1277110)，可以麻煩刪除嗎？

2023-03-03 14:08 UTC, chia7712 commented on common/src/main/java/org/astraea/common/metrics/collector/LocalMetricCollector.java
>      this.mBeanClients = new ConcurrentHashMap<>(mBeanClients);
可否讓傳入的`mBeanClients`換個名字避免混淆使用

2023-03-03 14:09 UTC, chia7712 commented on common/src/main/java/org/astraea/common/metrics/collector/LocalMetricCollector.java
> +    delayedWorks.add(new DelayedIdentity(Duration.ZERO, identity));
這算是一個蠻嚴重的bug，可否補一下測試？

2023-03-03 17:59 UTC, chia7712 commented on common/src/test/java/org/astraea/common/metrics/collector/MetricCollectorTest.java
> +      ((LocalMetricCollector) collector).registerJmx(1, socket);
這邊也檢查一下`collector.listIdentities().size())`是不是比較好？

2023-03-04 03:16 UTC, chia7712 approved these changes
LGTM and nice finding!

2023-03-04 03:22 UTC, chinghongfang approved these changes

2023-03-04 03:22 UTC, merged